version: "3"
services:
   selenium-hub:
        image: selenium/hub
        container_name: selenium-hub
        ports:
          - 4444:4444
   chrome:
        image: selenium/node-chrome
        depends_on:
          - selenium-hub
        environment:
          - HUB_HOST=selenium-hub
          - HUB_PORT=4444
        ports:
          - 5910:5910
   firefox:
        image: selenium/node-firefox
        depends_on:
          - selenium-hub
        environment:
          - HUB_HOST=selenium-hub
          - HUB_PORT=4444
        ports:
          - 5911:5911
   mvnSetup:
        image: maven
        env_file:
            - ./execution-settings.env
        volumes:
            - ./script:/var/tmp/script
            - $HOME/.m2:/root/.m2
        working_dir: /var/tmp/script
        command:
          - sh
          - '-c'
          - "mvn verify -Dwebdriver.remote.url=http://selenium-hub:4444/wd/hub -Dwebdriver.remote.driver=$${REMOTE_DRIVER} \
               -Dwebdriver.remote.os=$${REMOTE_GRID_OS} -Dwebdriver.base.url=$${BASE_URL} -Dtest.tagnames=$${TAG_NAME} -Dmaven.test.skip=false"
        ports:
          - 7070:7070
